name: flutter_twilio_conversations_platform_interface
description: A common platform interface for the flutter_twilio_conversations plugin.
author: Flutter Team <flutter-dev@googlegroups.com>
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: '>=1.17.0'